version: '3.9'

services:
  db:
    image: postgres
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: ./.docker/dockerfiles/python.dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env