version: '3.9'

services:
  postgresdb:
    restart: always
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/2-create_tables.sql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: userAdmin
      POSTGRES_PASSWORD: mypassword
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  pythonback:
    image: python:3
    container_name: pythonback
    volumes:
      - ./pythonback:/pythonback
    working_dir: /pythonback
    command: bash -c "pip install -r requirements.txt && python -u pythonback.py"
    depends_on:
      - postgresdb
    environment:
      DATABASE_HOST: postgresdb
      DATABASE_PORT: 5432
      DATABASE_USER: userAdmin
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydatabase
  web:
    build:
      context: .
      dockerfile: ./.docker/dockerfiles/python.dockerfile
    command: bash -c "pip install -r ./pythonback/requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pythonback
volumes:
  postgres_data:
